name: Release CI

on:
  push:
    tags:
      - "**"

jobs:
  create-release:
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      RELEASE_UPLOAD_ID: ${{ steps.create_release.outputs.id }}

    steps:
      - uses: actions/checkout@v2

      - name: Get tag version
        id: tag_version
        run: |
          TAG_NAME=$(git describe --tags --abbrev=0)
          echo "::set-output name=tag_name::${TAG_NAME}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.tag_name }}
          release_name: Release ${{ steps.tag_version.outputs.tag_name }}
          body: "See the assets to download this version and install."

  build-tauri:
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # - name: install dependencies (ubuntu only)
      #   if: matrix.platform == 'ubuntu-latest'
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y libwebkit2gtk-4.0-dev libappindicator3-dev libasound2-dev librsvg2-dev patchelf

      - name: Install app dependencies and build it
        run: bun install && bun run tauri build
      - uses: tauri-apps/tauri-action@v0
        with:
          releaseId: ${{ needs.create-release.outputs.RELEASE_UPLOAD_ID }}
